# Default scene settings. This script default is 1 (IsaacSim), so if you change
# the meters per unit or up axis, you need to alter the coordinates and rotations.

# IsaacSim default is 1, Code is 0.01
stage_unit_setting:
  settings.set_stage_meters_per_unit:
    meters_per_unit: 1

# IsaacSim default is "Z"", Code is "Y"
stage_up_axis_setting:
  settings.set_stage_up_axis:
    up_axis: "Z"

# This YAML script example demonstrates:
# Creating materials, and applying them to objects in a scene with a randomizer

# Create the materials to apply to the objects
mats:
  create.material_omnipbr:
    diffuse:
      distribution.uniform:
          lower: [0, 0, 0]
          upper: [1, 1, 1]
    count: 100

# Create the objects in the scene
spheres:
  create.sphere:
    scale: 0.2
    position:
      distribution.uniform:
        lower: [-1, -1, -1]
        upper: [1, 1, 1]
    count: 100

plane:
  create.plane:
    semantics: [["class", "plane"]]
    position: [0, 0, -1.5]
    visible: true
    scale: 100

# Create the camera and render product
camera:
  create.camera:
    position: [5, 0, 0]

render_product:
  create.render_product:
    camera: camera
    resolution: [1024, 1024]

# Create the writer and initialize
writer:
  writers.get:
    name: "BasicWriter"
    init_params:
      output_dir: "_output_yaml/TutorialRandomizerMaterials/"
      rgb: True

writer_attach:
  writer.attach:
    render_products: render_product

# Register a randomizer that sets the materials of the spheres
register_materials:
  randomizer.register:
    get_spheres:
      inputs:
        spheres: null
        mats: null
      with.spheres:
        randomizer.materials:
          materials: mats

# Set the trigger as on_frame, setting subframes to accumulate frames for a
# higher quality render
trigger:
  trigger.on_frame:
    max_execs: 20
    rt_subframes: 3

# When the trigger executes, apply the randomizer
with_trigger:
  with.trigger:
    randomizer.get_spheres:
      spheres: spheres
      mats: mats